Importing Libraries


In [110]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


Import Dataset

In [111]:

import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.

if os.environ.get('RUNTIME_ENV_LOCATION_TYPE') == 'external':
    endpoint_d3ea0b23de6d4851a31b8da87e9c1590 = 'https://s3.us.cloud-object-storage.appdomain.cloud'
else:
    endpoint_d3ea0b23de6d4851a31b8da87e9c1590 = 'https://s3.private.us.cloud-object-storage.appdomain.cloud'

client_d3ea0b23de6d4851a31b8da87e9c1590 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='47z23iJ4BrOWVyZNvnSp_VZ59AFoD9wq-tNclZu0YlLe',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url=endpoint_d3ea0b23de6d4851a31b8da87e9c1590)

body = client_d3ea0b23de6d4851a31b8da87e9c1590.get_object(Bucket='phishingwebsites-donotdelete-pr-hvzzksdmih22o6',Key='dataset_website.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

ds = pd.read_csv(body)
ds.head()

index  having_IPhaving_IP_Address  URLURL_Length  Shortining_Service  \
0      1                          -1              1                   1   
1      2                           1              1                   1   
2      3                           1              0                   1   
3      4                           1              0                   1   
4      5                           1              0                  -1   

   having_At_Symbol  double_slash_redirecting  Prefix_Suffix  \
0                 1                        -1             -1   
1                 1                         1             -1   
2                 1                         1             -1   
3                 1                         1             -1   
4                 1                         1             -1   

   having_Sub_Domain  SSLfinal_State  Domain_registeration_length  ...  \
0                 -1              -1                           -1  ...   
1                  0               1                           -1  ...   
2                 -1              -1                           -1  ...   
3                 -1              -1                            1  ...   
4                  1               1                           -1  ...   

   popUpWidnow  Iframe  age_of_domain  DNSRecord  web_traffic  Page_Rank  \
0            1       1             -1         -1           -1         -1   
1            1       1             -1         -1            0         -1   
2            1       1              1         -1            1         -1   
3            1       1             -1         -1            1         -1   
4           -1       1             -1         -1            0         -1   

   Google_Index  Links_pointing_to_page  Statistical_report  Result  
0             1                       1                  -1      -1  
1             1                       1                   1      -1  
2             1                       0                  -1      -1  
3             1                      -1                   1      -1  
4             1                       1                   1       1  

[5 rows x 32 columns]

In [112]:
#Analysing the data using pandas and Checking if the dataset contains any Null values.
ds.info()
ds.isnull().any() #no nullvalues

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11055 entries, 0 to 11054
Data columns (total 32 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   index                        11055 non-null  int64
 1   having_IPhaving_IP_Address   11055 non-null  int64
 2   URLURL_Length                11055 non-null  int64
 3   Shortining_Service           11055 non-null  int64
 4   having_At_Symbol             11055 non-null  int64
 5   double_slash_redirecting     11055 non-null  int64
 6   Prefix_Suffix                11055 non-null  int64
 7   having_Sub_Domain            11055 non-null  int64
 8   SSLfinal_State               11055 non-null  int64
 9   Domain_registeration_length  11055 non-null  int64
 10  Favicon                      11055 non-null  int64
 11  port                         11055 non-null  int64
 12  HTTPS_token                  11055 non-null  int64
 13  Request_URL                  11055 non-null  i

index                          False
having_IPhaving_IP_Address     False
URLURL_Length                  False
Shortining_Service             False
having_At_Symbol               False
double_slash_redirecting       False
Prefix_Suffix                  False
having_Sub_Domain              False
SSLfinal_State                 False
Domain_registeration_length    False
Favicon                        False
port                           False
HTTPS_token                    False
Request_URL                    False
URL_of_Anchor                  False
Links_in_tags                  False
SFH                            False
Submitting_to_email            False
Abnormal_URL                   False
Redirect                       False
on_mouseover                   False
RightClick                     False
popUpWidnow                    False
Iframe                         False
age_of_domain                  False
DNSRecord                      False
web_traffic                    False
P

Taking care of missing data

In [113]:
ds.isnull().any()   #no missing data in the dataset

index                          False
having_IPhaving_IP_Address     False
URLURL_Length                  False
Shortining_Service             False
having_At_Symbol               False
double_slash_redirecting       False
Prefix_Suffix                  False
having_Sub_Domain              False
SSLfinal_State                 False
Domain_registeration_length    False
Favicon                        False
port                           False
HTTPS_token                    False
Request_URL                    False
URL_of_Anchor                  False
Links_in_tags                  False
SFH                            False
Submitting_to_email            False
Abnormal_URL                   False
Redirect                       False
on_mouseover                   False
RightClick                     False
popUpWidnow                    False
Iframe                         False
age_of_domain                  False
DNSRecord                      False
web_traffic                    False
P

No need of applying label/one hot encoding as there are no categorical columns in the dataset.

Feature scaling is not required as data is already present in the same range.

Splitting data as independent and dependent

In [114]:
#Splitting data as independent and dependent
#removing index column in independent dataset
x=ds.iloc[:,1:31].values
y=ds.iloc[:,-1].values
print(x,y)

[[-1  1  1 ...  1  1 -1]
 [ 1  1  1 ...  1  1  1]
 [ 1  0  1 ...  1  0 -1]
 ...
 [ 1 -1  1 ...  1  0  1]
 [-1 -1  1 ...  1  1  1]
 [-1 -1  1 ... -1  1 -1]] [-1 -1 -1 ... -1 -1 -1]


In [115]:
y=ds.iloc[:,-1].values
y

array([-1, -1, -1, ..., -1, -1, -1])

Splitting data into train and test 

In [116]:
#Splitting data into train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

MODEL BUILDING -

Since the output (result) is  categorical , it comes under classification model.

Training and Testing the model -

1. LOGISTIC REGRESSION -

In [117]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)

LogisticRegression()

In [118]:
lr.fit(x_train,y_train)

LogisticRegression()

In [119]:
y_pred1=lr.predict(x_test)

In [120]:
y_pred1=lr.predict(x_test)
from sklearn.metrics import accuracy_score
log_reg=accuracy_score(y_test,y_pred1)
log_reg

0.9167797376752601

2. KNN-euclidian distance

In [121]:
from sklearn.neighbors import KNeighborsClassifier
kn1=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)  


In [122]:
kn1.fit(x_train,y_train)

KNeighborsClassifier()

In [123]:
y_pred2=kn1.predict(x_test)
from sklearn.metrics import accuracy_score
knn_euc=accuracy_score(y_test,y_pred2)
knn_euc


0.9416553595658074

3. KNN-manhattan distance

In [124]:
kn2=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=1)
kn2.fit(x_train,y_train) 

KNeighborsClassifier(p=1)

In [125]:
y_pred3=kn2.predict(x_test)
from sklearn.metrics import accuracy_score
knn_man=accuracy_score(y_test,y_pred3)
knn_man

0.9488919041157847

4. SVM -rbf

In [126]:
from sklearn.svm import SVC
svm1=SVC(kernel='rbf')
svm1.fit(x_train,y_train) 

SVC()

In [127]:
y_pred4=svm1.predict(x_test)
from sklearn.metrics import accuracy_score
svm_rbf=accuracy_score(y_test,y_pred4)
svm_rbf

0.9407507914970602

5. SVM -sigmoid

In [128]:
svm2=SVC(kernel='sigmoid')
svm2.fit(x_train,y_train) 

SVC(kernel='sigmoid')

In [129]:
y_pred5=svm2.predict(x_test)
from sklearn.metrics import accuracy_score
svm_sig=accuracy_score(y_test,y_pred5)
svm_sig

0.8326549072817729

6. DECISION TREE

In [130]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [131]:
y_pred6=dt.predict(x_test)
from sklearn.metrics import accuracy_score
dec_tree=accuracy_score(y_test,y_pred6)
dec_tree

0.9606512890094979

7. RANDOM FOREST

In [132]:
from sklearn.ensemble import RandomForestRegressor
Rf=RandomForestRegressor(n_estimators=10,random_state=0,n_jobs=-1)     
Rf.fit(x_train,y_train)

RandomForestRegressor(n_estimators=10, n_jobs=-1, random_state=0)

In [133]:
y_pred7=Rf.predict(x_test)
from sklearn.metrics import accuracy_score
rf=accuracy_score(y_test,y_pred7.round())
rf

0.9285391225689733

8. NAIVE BAYES

In [134]:
from sklearn.naive_bayes import GaussianNB
gb=GaussianNB()
gb.fit(x_train,y_train)

GaussianNB()

In [135]:
y_pred8=gb.predict(x_test)
from sklearn.metrics import accuracy_score
nb=accuracy_score(y_test,y_pred1)
nb

0.9167797376752601

Model Comparision

In [136]:
models = pd.DataFrame({
    'Model': [ 'Logistic Regression', 'KNN-eiclidian distance','KNN-manhattan distance','Naive Bayes','SVM-rbf','SVM-sigmoid','Decision Tree','Random Forest'],
    'Test Score': [ log_reg,knn_euc,knn_man,nb,svm_rbf,svm_sig,dec_tree,rf]})
models.sort_values(by='Test Score', ascending=False)

Model  Test Score
6           Decision Tree    0.960651
2  KNN-manhattan distance    0.948892
1  KNN-eiclidian distance    0.941655
4                 SVM-rbf    0.940751
7           Random Forest    0.928539
0     Logistic Regression    0.916780
3             Naive Bayes    0.916780
5             SVM-sigmoid    0.832655

To avoid overfitting , the model which is considered here is LOGISTIC REGRESSION

In [176]:
from ibm_watson_machine_learning import APIClient
wml_credentials = {
                    "url": "https://us-south.ml.cloud.ibm.com",
                    "apikey":"DIKPkdOP4HJZYQhCmxxnCq20_eSwpIN97Qet7hx12AiN"
                   }
client = APIClient(wml_credentials)

In [177]:
def guid_from_space_name(client,space_name):
    space=client.spaces.get_details()
    return(next(item for item in space['resources'] if item['entity']["name"]==space_name)['metadata']['id'])

In [178]:
space_uid = guid_from_space_name(client, 'ibm_phishing')
print("SpaceUID = " + space_uid)

SpaceUID = 8b0ee1f3-72d5-493f-a916-aebf0d9a4ac1


In [179]:
client.set.default_space(space_uid)

'SUCCESS'

In [180]:
client.software_specifications.list()

-----------------------------  ------------------------------------  ----
NAME                           ASSET_ID                              TYPE
default_py3.6                  0062b8c9-8b7d-44a0-a9b9-46c416adcbd9  base
pytorch-onnx_1.3-py3.7-edt     069ea134-3346-5748-b513-49120e15d288  base
scikit-learn_0.20-py3.6        09c5a1d0-9c1e-4473-a344-eb7b665ff687  base
spark-mllib_3.0-scala_2.12     09f4cff0-90a7-5899-b9ed-1ef348aebdee  base
ai-function_0.1-py3.6          0cdb0f1e-5376-4f4d-92dd-da3b69aa9bda  base
shiny-r3.6                     0e6e79df-875e-4f24-8ae9-62dcc2148306  base
tensorflow_2.4-py3.7-horovod   1092590a-307d-563d-9b62-4eb7d64b3f22  base
pytorch_1.1-py3.6              10ac12d6-6b30-4ccd-8392-3e922c096a92  base
tensorflow_1.15-py3.6-ddl      111e41b3-de2d-5422-a4d6-bf776828c4b7  base
scikit-learn_0.22-py3.6        154010fa-5b3b-4ac1-82af-4d5ee5abbc85  base
default_r3.6                   1b70aec3-ab34-4b87-8aa0-a4a3c8296a36  base
pytorch-onnx_1.3-py3.6         1bc6029

In [181]:
import pickle
pickle.dump(lr,open('Phishing_Website.pkl','wb'))

In [182]:
MODEL_NAME = 'phishing'
DEPLOYMENT_NAME = 'ibm_phishing'
phishing_MODEL = lr

In [183]:
software_spec=client.software_specifications.get_uid_by_name("default_py3.7_opence")

In [184]:
# Setup model meta
model_props = {
    client.repository.ModelMetaNames.NAME: MODEL_NAME,
    client.repository.ModelMetaNames.TYPE: 'scikit-learn_0.23',
    client.repository.ModelMetaNames.SOFTWARE_SPEC_UID: software_spec_uid
}

In [185]:
#Save model
model_details = client.repository.store_model(
    model=phishing_MODEL,
    meta_props=model_props,
    training_data=x_train,
    training_target=y_train
)




Note: Warnings!! :  Software specification tensorflow_1.15-py3.6 specified for the wml_model is deprecated and will be removed in the future. We recommend you use a supported software specification. See Supported Frameworks https://dataplatform.cloud.ibm.com/docs/content/wsj/analyze-data/pm_service_supported_frameworks.html.


In [186]:
model_details

{'entity': {'label_column': 'l1',
  'software_spec': {'id': '2b73a275-7cbf-420b-a912-eae7f436e0bc',
   'name': 'tensorflow_1.15-py3.6'},
  'training_data_references': [{'connection': {'access_key_id': 'not_applicable',
     'endpoint_url': 'not_applicable',
     'secret_access_key': 'not_applicable'},
    'id': '1',
    'location': {},
    'schema': {'fields': [{'name': 'f0', 'type': 'int'},
      {'name': 'f1', 'type': 'int'},
      {'name': 'f2', 'type': 'int'},
      {'name': 'f3', 'type': 'int'},
      {'name': 'f4', 'type': 'int'},
      {'name': 'f5', 'type': 'int'},
      {'name': 'f6', 'type': 'int'},
      {'name': 'f7', 'type': 'int'},
      {'name': 'f8', 'type': 'int'},
      {'name': 'f9', 'type': 'int'},
      {'name': 'f10', 'type': 'int'},
      {'name': 'f11', 'type': 'int'},
      {'name': 'f12', 'type': 'int'},
      {'name': 'f13', 'type': 'int'},
      {'name': 'f14', 'type': 'int'},
      {'name': 'f15', 'type': 'int'},
      {'name': 'f16', 'type': 'int'},
      

In [187]:
model_uid = client.repository.get_model_uid(model_details); model_uid

'0dbef068-557b-4dc7-8338-d6bbbafa3737'

In [188]:
# Set meta
deployment_props = {
    client.deployments.ConfigurationMetaNames.NAME:DEPLOYMENT_NAME,
    client.deployments.ConfigurationMetaNames.ONLINE: {}
}

In [189]:
# Deploy
deployment = client.deployments.create(
    artifact_uid=model_uid,
    meta_props=deployment_props
)

{"trace":"2f25f8b6009c3275480d7d28cf77f686","errors":[{"code":"unsupported_software_specification_details","message":"Software specification tensorflow_1.15-py3.6 for model is not supported. Supported software specifications for model are: default_py3.7, default_py3.7_opence, default_py3.8. Retry deployment after saving the model with supported software specification."}]}


--------------------------
Deployment creation failed
--------------------------




WMLClientError: Deployment creation failed. Error: 400. {"trace":"2f25f8b6009c3275480d7d28cf77f686","errors":[{"code":"unsupported_software_specification_details","message":"Software specification tensorflow_1.15-py3.6 for model is not supported. Supported software specifications for model are: default_py3.7, default_py3.7_opence, default_py3.8. Retry deployment after saving the model with supported software specification."}]}

ACCURACY OF DECISION TREE MODEL IS HIGHEST 

In [28]:
import pickle
pickle.dump(lr,open('Phishing_Website.pkl','wb'))